name: PR Lint Check

on: 
  pull_request_target:
    branches:
      - master
      
jobs:
  linter_name:
    name: runner / black
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
     - uses: wemake-services/wemake-python-styleguide@0.15.3
       with:
         reporter: 'github-pr-review'
       env:
         GITHUB_TOKEN: ${{ secrets.github_token }}

